version: '3'
services:
  web:
    build:
      context: docker/nginx
      dockerfile: prod/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - public-data:/var/www/public
    depends_on:
      - api
  api:
    build:
      context: ./
      dockerfile: docker/php-fpm/production/Dockerfile
    volumes:
        - public-data:/var/www/public
#  daemon:
#    build:
#      context: ./
#      dockerfile: docker/php-fpm/production/Dockerfile
#    restart: always
#    command:
#      -
volumes:
  public-data:
