version: '3'
services:
  web:
    build:
      context: docker/nginx
      dockerfile: prod/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - public-data:/var/www/public
    depends_on:
      - api
  api:
    build:
      context: ./
      dockerfile: docker/php-fpm/production/Dockerfile
    volumes:
        - public-data:/var/www/public
  daemon:
    build:
      context: ./
      dockerfile: docker/php-fpm/production/Dockerfile
    depends_on:
      - api
    links:
      - database
    command: [ sh, -c, php bin/console messenger:consume async --limit=731 ]
    restart: always
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  public-data:
