version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
  api:
    build:
      context: ./
      dockerfile: docker/php-fpm/development/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres:11-alpine
    env_file:
      - .env
    ports:
      - "54320:5432"
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"
